# Generated by Django 5.1 on 2024-08-10 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampHistory',
            fields=[
                ('_campID', models.CharField(default='100000', max_length=1000)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='none', max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=1000)),
                ('is_verified', models.BooleanField(default=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LatestCamp',
            fields=[
                ('camp_secret', models.CharField(default='none', max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('expire', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=1000)),
                ('terms_cond', models.TextField()),
                ('is_format', models.BooleanField(default=False)),
                ('_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('username', models.CharField(default='None', max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('upi', models.CharField(default='none', max_length=100)),
                ('wallet', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw_history',
            fields=[
                ('email', models.CharField(default='none', max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
            ],
        ),
    ]
