# Generated by Django 5.1 on 2024-08-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camphistory',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
