# Generated by Django 5.1 on 2024-09-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='camphistory',
            name='ip_address',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
